// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockHookOnStop is an autogenerated mock type for the HookOnStop type
type MockHookOnStop struct {
	mock.Mock
}

type MockHookOnStop_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHookOnStop) EXPECT() *MockHookOnStop_Expecter {
	return &MockHookOnStop_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockHookOnStop) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockHookOnStop_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockHookOnStop_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockHookOnStop_Expecter) Name() *MockHookOnStop_Name_Call {
	return &MockHookOnStop_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockHookOnStop_Name_Call) Run(run func()) *MockHookOnStop_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHookOnStop_Name_Call) Return(_a0 string) *MockHookOnStop_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHookOnStop_Name_Call) RunAndReturn(run func() string) *MockHookOnStop_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnStop provides a mock function with given fields: s
func (_m *MockHookOnStop) OnStop(s *akira.Server) {
	_m.Called(s)
}

// MockHookOnStop_OnStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnStop'
type MockHookOnStop_OnStop_Call struct {
	*mock.Call
}

// OnStop is a helper method to define mock.On call
//   - s *akira.Server
func (_e *MockHookOnStop_Expecter) OnStop(s interface{}) *MockHookOnStop_OnStop_Call {
	return &MockHookOnStop_OnStop_Call{Call: _e.mock.On("OnStop", s)}
}

func (_c *MockHookOnStop_OnStop_Call) Run(run func(s *akira.Server)) *MockHookOnStop_OnStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server))
	})
	return _c
}

func (_c *MockHookOnStop_OnStop_Call) Return() *MockHookOnStop_OnStop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHookOnStop_OnStop_Call) RunAndReturn(run func(*akira.Server)) *MockHookOnStop_OnStop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHookOnStop creates a new instance of MockHookOnStop. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHookOnStop(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHookOnStop {
	mock := &MockHookOnStop{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
