// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockHookOnServerStop is an autogenerated mock type for the HookOnServerStop type
type MockHookOnServerStop struct {
	mock.Mock
}

type MockHookOnServerStop_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHookOnServerStop) EXPECT() *MockHookOnServerStop_Expecter {
	return &MockHookOnServerStop_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockHookOnServerStop) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockHookOnServerStop_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockHookOnServerStop_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockHookOnServerStop_Expecter) Name() *MockHookOnServerStop_Name_Call {
	return &MockHookOnServerStop_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockHookOnServerStop_Name_Call) Run(run func()) *MockHookOnServerStop_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHookOnServerStop_Name_Call) Return(_a0 string) *MockHookOnServerStop_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHookOnServerStop_Name_Call) RunAndReturn(run func() string) *MockHookOnServerStop_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnServerStop provides a mock function with given fields: s
func (_m *MockHookOnServerStop) OnServerStop(s *akira.Server) {
	_m.Called(s)
}

// MockHookOnServerStop_OnServerStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnServerStop'
type MockHookOnServerStop_OnServerStop_Call struct {
	*mock.Call
}

// OnServerStop is a helper method to define mock.On call
//   - s *akira.Server
func (_e *MockHookOnServerStop_Expecter) OnServerStop(s interface{}) *MockHookOnServerStop_OnServerStop_Call {
	return &MockHookOnServerStop_OnServerStop_Call{Call: _e.mock.On("OnServerStop", s)}
}

func (_c *MockHookOnServerStop_OnServerStop_Call) Run(run func(s *akira.Server)) *MockHookOnServerStop_OnServerStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server))
	})
	return _c
}

func (_c *MockHookOnServerStop_OnServerStop_Call) Return() *MockHookOnServerStop_OnServerStop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHookOnServerStop_OnServerStop_Call) RunAndReturn(run func(*akira.Server)) *MockHookOnServerStop_OnServerStop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHookOnServerStop creates a new instance of MockHookOnServerStop. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHookOnServerStop(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHookOnServerStop {
	mock := &MockHookOnServerStop{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
