// Code generated by mockery. DO NOT EDIT.

package mocks

import "github.com/stretchr/testify/mock"

// MockHook is an autogenerated mock type for the Hook type
type MockHook struct {
	mock.Mock
}

type MockHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHook) EXPECT() *MockHook_Expecter {
	return &MockHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockHook_Expecter) Name() *MockHook_Name_Call {
	return &MockHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockHook_Name_Call) Run(run func()) *MockHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHook_Name_Call) Return(_a0 string) *MockHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHook_Name_Call) RunAndReturn(run func() string) *MockHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHook creates a new instance of MockHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHook {
	mock := &MockHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
