// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"github.com/gsalomao/akira"
	"github.com/stretchr/testify/mock"
)

// MockHookOnConnectionClose is an autogenerated mock type for the HookOnConnectionClose type
type MockHookOnConnectionClose struct {
	mock.Mock
}

type MockHookOnConnectionClose_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHookOnConnectionClose) EXPECT() *MockHookOnConnectionClose_Expecter {
	return &MockHookOnConnectionClose_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockHookOnConnectionClose) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockHookOnConnectionClose_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockHookOnConnectionClose_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockHookOnConnectionClose_Expecter) Name() *MockHookOnConnectionClose_Name_Call {
	return &MockHookOnConnectionClose_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockHookOnConnectionClose_Name_Call) Run(run func()) *MockHookOnConnectionClose_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHookOnConnectionClose_Name_Call) Return(_a0 string) *MockHookOnConnectionClose_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHookOnConnectionClose_Name_Call) RunAndReturn(run func() string) *MockHookOnConnectionClose_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnConnectionClose provides a mock function with given fields: s, l, err
func (_m *MockHookOnConnectionClose) OnConnectionClose(s *akira.Server, l akira.Listener, err error) {
	_m.Called(s, l, err)
}

// MockHookOnConnectionClose_OnConnectionClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConnectionClose'
type MockHookOnConnectionClose_OnConnectionClose_Call struct {
	*mock.Call
}

// OnConnectionClose is a helper method to define mock.On call
//   - s *akira.Server
//   - l akira.Listener
//   - err error
func (_e *MockHookOnConnectionClose_Expecter) OnConnectionClose(s interface{}, l interface{}, err interface{}) *MockHookOnConnectionClose_OnConnectionClose_Call {
	return &MockHookOnConnectionClose_OnConnectionClose_Call{Call: _e.mock.On("OnConnectionClose", s, l, err)}
}

func (_c *MockHookOnConnectionClose_OnConnectionClose_Call) Run(run func(s *akira.Server, l akira.Listener, err error)) *MockHookOnConnectionClose_OnConnectionClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server), args[1].(akira.Listener), args[2].(error))
	})
	return _c
}

func (_c *MockHookOnConnectionClose_OnConnectionClose_Call) Return() *MockHookOnConnectionClose_OnConnectionClose_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHookOnConnectionClose_OnConnectionClose_Call) RunAndReturn(run func(*akira.Server, akira.Listener, error)) *MockHookOnConnectionClose_OnConnectionClose_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHookOnConnectionClose creates a new instance of MockHookOnConnectionClose. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHookOnConnectionClose(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHookOnConnectionClose {
	mock := &MockHookOnConnectionClose{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
