// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"github.com/gsalomao/akira"
	"github.com/stretchr/testify/mock"
)

// MockHookOnConnectionClosed is an autogenerated mock type for the HookOnConnectionClosed type
type MockHookOnConnectionClosed struct {
	mock.Mock
}

type MockHookOnConnectionClosed_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHookOnConnectionClosed) EXPECT() *MockHookOnConnectionClosed_Expecter {
	return &MockHookOnConnectionClosed_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockHookOnConnectionClosed) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockHookOnConnectionClosed_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockHookOnConnectionClosed_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockHookOnConnectionClosed_Expecter) Name() *MockHookOnConnectionClosed_Name_Call {
	return &MockHookOnConnectionClosed_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockHookOnConnectionClosed_Name_Call) Run(run func()) *MockHookOnConnectionClosed_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHookOnConnectionClosed_Name_Call) Return(_a0 string) *MockHookOnConnectionClosed_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHookOnConnectionClosed_Name_Call) RunAndReturn(run func() string) *MockHookOnConnectionClosed_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnConnectionClosed provides a mock function with given fields: s, l, err
func (_m *MockHookOnConnectionClosed) OnConnectionClosed(s *akira.Server, l akira.Listener, err error) {
	_m.Called(s, l, err)
}

// MockHookOnConnectionClosed_OnConnectionClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConnectionClosed'
type MockHookOnConnectionClosed_OnConnectionClosed_Call struct {
	*mock.Call
}

// OnConnectionClosed is a helper method to define mock.On call
//   - s *akira.Server
//   - l akira.Listener
//   - err error
func (_e *MockHookOnConnectionClosed_Expecter) OnConnectionClosed(s interface{}, l interface{}, err interface{}) *MockHookOnConnectionClosed_OnConnectionClosed_Call {
	return &MockHookOnConnectionClosed_OnConnectionClosed_Call{Call: _e.mock.On("OnConnectionClosed", s, l, err)}
}

func (_c *MockHookOnConnectionClosed_OnConnectionClosed_Call) Run(run func(s *akira.Server, l akira.Listener, err error)) *MockHookOnConnectionClosed_OnConnectionClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server), args[1].(akira.Listener), args[2].(error))
	})
	return _c
}

func (_c *MockHookOnConnectionClosed_OnConnectionClosed_Call) Return() *MockHookOnConnectionClosed_OnConnectionClosed_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHookOnConnectionClosed_OnConnectionClosed_Call) RunAndReturn(run func(*akira.Server, akira.Listener, error)) *MockHookOnConnectionClosed_OnConnectionClosed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHookOnConnectionClosed creates a new instance of MockHookOnConnectionClosed. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHookOnConnectionClosed(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHookOnConnectionClosed {
	mock := &MockHookOnConnectionClosed{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
