// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockHookOnConnectionOpened is an autogenerated mock type for the HookOnConnectionOpened type
type MockHookOnConnectionOpened struct {
	mock.Mock
}

type MockHookOnConnectionOpened_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHookOnConnectionOpened) EXPECT() *MockHookOnConnectionOpened_Expecter {
	return &MockHookOnConnectionOpened_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockHookOnConnectionOpened) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockHookOnConnectionOpened_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockHookOnConnectionOpened_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockHookOnConnectionOpened_Expecter) Name() *MockHookOnConnectionOpened_Name_Call {
	return &MockHookOnConnectionOpened_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockHookOnConnectionOpened_Name_Call) Run(run func()) *MockHookOnConnectionOpened_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHookOnConnectionOpened_Name_Call) Return(_a0 string) *MockHookOnConnectionOpened_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHookOnConnectionOpened_Name_Call) RunAndReturn(run func() string) *MockHookOnConnectionOpened_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnConnectionOpened provides a mock function with given fields: s, l
func (_m *MockHookOnConnectionOpened) OnConnectionOpened(s *akira.Server, l akira.Listener) {
	_m.Called(s, l)
}

// MockHookOnConnectionOpened_OnConnectionOpened_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConnectionOpened'
type MockHookOnConnectionOpened_OnConnectionOpened_Call struct {
	*mock.Call
}

// OnConnectionOpened is a helper method to define mock.On call
//   - s *akira.Server
//   - l akira.Listener
func (_e *MockHookOnConnectionOpened_Expecter) OnConnectionOpened(s interface{}, l interface{}) *MockHookOnConnectionOpened_OnConnectionOpened_Call {
	return &MockHookOnConnectionOpened_OnConnectionOpened_Call{Call: _e.mock.On("OnConnectionOpened", s, l)}
}

func (_c *MockHookOnConnectionOpened_OnConnectionOpened_Call) Run(run func(s *akira.Server, l akira.Listener)) *MockHookOnConnectionOpened_OnConnectionOpened_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server), args[1].(akira.Listener))
	})
	return _c
}

func (_c *MockHookOnConnectionOpened_OnConnectionOpened_Call) Return() *MockHookOnConnectionOpened_OnConnectionOpened_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHookOnConnectionOpened_OnConnectionOpened_Call) RunAndReturn(run func(*akira.Server, akira.Listener)) *MockHookOnConnectionOpened_OnConnectionOpened_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHookOnConnectionOpened creates a new instance of MockHookOnConnectionOpened. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHookOnConnectionOpened(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHookOnConnectionOpened {
	mock := &MockHookOnConnectionOpened{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
