// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockOnConnectionOpenHook is an autogenerated mock type for the OnConnectionOpenHook type
type MockOnConnectionOpenHook struct {
	mock.Mock
}

type MockOnConnectionOpenHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnConnectionOpenHook) EXPECT() *MockOnConnectionOpenHook_Expecter {
	return &MockOnConnectionOpenHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnConnectionOpenHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnConnectionOpenHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnConnectionOpenHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnConnectionOpenHook_Expecter) Name() *MockOnConnectionOpenHook_Name_Call {
	return &MockOnConnectionOpenHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnConnectionOpenHook_Name_Call) Run(run func()) *MockOnConnectionOpenHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnConnectionOpenHook_Name_Call) Return(_a0 string) *MockOnConnectionOpenHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnConnectionOpenHook_Name_Call) RunAndReturn(run func() string) *MockOnConnectionOpenHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnConnectionOpen provides a mock function with given fields: s, l
func (_m *MockOnConnectionOpenHook) OnConnectionOpen(s *akira.Server, l akira.Listener) error {
	ret := _m.Called(s, l)

	var r0 error
	if rf, ok := ret.Get(0).(func(*akira.Server, akira.Listener) error); ok {
		r0 = rf(s, l)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOnConnectionOpenHook_OnConnectionOpen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConnectionOpen'
type MockOnConnectionOpenHook_OnConnectionOpen_Call struct {
	*mock.Call
}

// OnConnectionOpen is a helper method to define mock.On call
//   - s *akira.Server
//   - l akira.Listener
func (_e *MockOnConnectionOpenHook_Expecter) OnConnectionOpen(s interface{}, l interface{}) *MockOnConnectionOpenHook_OnConnectionOpen_Call {
	return &MockOnConnectionOpenHook_OnConnectionOpen_Call{Call: _e.mock.On("OnConnectionOpen", s, l)}
}

func (_c *MockOnConnectionOpenHook_OnConnectionOpen_Call) Run(run func(s *akira.Server, l akira.Listener)) *MockOnConnectionOpenHook_OnConnectionOpen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server), args[1].(akira.Listener))
	})
	return _c
}

func (_c *MockOnConnectionOpenHook_OnConnectionOpen_Call) Return(_a0 error) *MockOnConnectionOpenHook_OnConnectionOpen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnConnectionOpenHook_OnConnectionOpen_Call) RunAndReturn(run func(*akira.Server, akira.Listener) error) *MockOnConnectionOpenHook_OnConnectionOpen_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnConnectionOpenHook creates a new instance of MockOnConnectionOpenHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnConnectionOpenHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnConnectionOpenHook {
	mock := &MockOnConnectionOpenHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
