// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"

	packet "github.com/gsalomao/akira/packet"
)

// MockOnConnectHook is an autogenerated mock type for the OnConnectHook type
type MockOnConnectHook struct {
	mock.Mock
}

type MockOnConnectHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnConnectHook) EXPECT() *MockOnConnectHook_Expecter {
	return &MockOnConnectHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnConnectHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnConnectHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnConnectHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnConnectHook_Expecter) Name() *MockOnConnectHook_Name_Call {
	return &MockOnConnectHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnConnectHook_Name_Call) Run(run func()) *MockOnConnectHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnConnectHook_Name_Call) Return(_a0 string) *MockOnConnectHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnConnectHook_Name_Call) RunAndReturn(run func() string) *MockOnConnectHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnConnect provides a mock function with given fields: c, p
func (_m *MockOnConnectHook) OnConnect(c *akira.Client, p *packet.Connect) error {
	ret := _m.Called(c, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(*akira.Client, *packet.Connect) error); ok {
		r0 = rf(c, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOnConnectHook_OnConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConnect'
type MockOnConnectHook_OnConnect_Call struct {
	*mock.Call
}

// OnConnect is a helper method to define mock.On call
//   - c *akira.Client
//   - p *packet.Connect
func (_e *MockOnConnectHook_Expecter) OnConnect(c interface{}, p interface{}) *MockOnConnectHook_OnConnect_Call {
	return &MockOnConnectHook_OnConnect_Call{Call: _e.mock.On("OnConnect", c, p)}
}

func (_c *MockOnConnectHook_OnConnect_Call) Run(run func(c *akira.Client, p *packet.Connect)) *MockOnConnectHook_OnConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Client), args[1].(*packet.Connect))
	})
	return _c
}

func (_c *MockOnConnectHook_OnConnect_Call) Return(_a0 error) *MockOnConnectHook_OnConnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnConnectHook_OnConnect_Call) RunAndReturn(run func(*akira.Client, *packet.Connect) error) *MockOnConnectHook_OnConnect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnConnectHook creates a new instance of MockOnConnectHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnConnectHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnConnectHook {
	mock := &MockOnConnectHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
