// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockOnConnectionOpenedHook is an autogenerated mock type for the OnConnectionOpenedHook type
type MockOnConnectionOpenedHook struct {
	mock.Mock
}

type MockOnConnectionOpenedHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnConnectionOpenedHook) EXPECT() *MockOnConnectionOpenedHook_Expecter {
	return &MockOnConnectionOpenedHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnConnectionOpenedHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnConnectionOpenedHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnConnectionOpenedHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnConnectionOpenedHook_Expecter) Name() *MockOnConnectionOpenedHook_Name_Call {
	return &MockOnConnectionOpenedHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnConnectionOpenedHook_Name_Call) Run(run func()) *MockOnConnectionOpenedHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnConnectionOpenedHook_Name_Call) Return(_a0 string) *MockOnConnectionOpenedHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnConnectionOpenedHook_Name_Call) RunAndReturn(run func() string) *MockOnConnectionOpenedHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnConnectionOpened provides a mock function with given fields: s, l
func (_m *MockOnConnectionOpenedHook) OnConnectionOpened(s *akira.Server, l akira.Listener) {
	_m.Called(s, l)
}

// MockOnConnectionOpenedHook_OnConnectionOpened_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConnectionOpened'
type MockOnConnectionOpenedHook_OnConnectionOpened_Call struct {
	*mock.Call
}

// OnConnectionOpened is a helper method to define mock.On call
//   - s *akira.Server
//   - l akira.Listener
func (_e *MockOnConnectionOpenedHook_Expecter) OnConnectionOpened(s interface{}, l interface{}) *MockOnConnectionOpenedHook_OnConnectionOpened_Call {
	return &MockOnConnectionOpenedHook_OnConnectionOpened_Call{Call: _e.mock.On("OnConnectionOpened", s, l)}
}

func (_c *MockOnConnectionOpenedHook_OnConnectionOpened_Call) Run(run func(s *akira.Server, l akira.Listener)) *MockOnConnectionOpenedHook_OnConnectionOpened_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server), args[1].(akira.Listener))
	})
	return _c
}

func (_c *MockOnConnectionOpenedHook_OnConnectionOpened_Call) Return() *MockOnConnectionOpenedHook_OnConnectionOpened_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOnConnectionOpenedHook_OnConnectionOpened_Call) RunAndReturn(run func(*akira.Server, akira.Listener)) *MockOnConnectionOpenedHook_OnConnectionOpened_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnConnectionOpenedHook creates a new instance of MockOnConnectionOpenedHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnConnectionOpenedHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnConnectionOpenedHook {
	mock := &MockOnConnectionOpenedHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
