// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockOnConnectionCloseHook is an autogenerated mock type for the OnConnectionCloseHook type
type MockOnConnectionCloseHook struct {
	mock.Mock
}

type MockOnConnectionCloseHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnConnectionCloseHook) EXPECT() *MockOnConnectionCloseHook_Expecter {
	return &MockOnConnectionCloseHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnConnectionCloseHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnConnectionCloseHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnConnectionCloseHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnConnectionCloseHook_Expecter) Name() *MockOnConnectionCloseHook_Name_Call {
	return &MockOnConnectionCloseHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnConnectionCloseHook_Name_Call) Run(run func()) *MockOnConnectionCloseHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnConnectionCloseHook_Name_Call) Return(_a0 string) *MockOnConnectionCloseHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnConnectionCloseHook_Name_Call) RunAndReturn(run func() string) *MockOnConnectionCloseHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnConnectionClose provides a mock function with given fields: s, l, err
func (_m *MockOnConnectionCloseHook) OnConnectionClose(s *akira.Server, l akira.Listener, err error) {
	_m.Called(s, l, err)
}

// MockOnConnectionCloseHook_OnConnectionClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConnectionClose'
type MockOnConnectionCloseHook_OnConnectionClose_Call struct {
	*mock.Call
}

// OnConnectionClose is a helper method to define mock.On call
//   - s *akira.Server
//   - l akira.Listener
//   - err error
func (_e *MockOnConnectionCloseHook_Expecter) OnConnectionClose(s interface{}, l interface{}, err interface{}) *MockOnConnectionCloseHook_OnConnectionClose_Call {
	return &MockOnConnectionCloseHook_OnConnectionClose_Call{Call: _e.mock.On("OnConnectionClose", s, l, err)}
}

func (_c *MockOnConnectionCloseHook_OnConnectionClose_Call) Run(run func(s *akira.Server, l akira.Listener, err error)) *MockOnConnectionCloseHook_OnConnectionClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server), args[1].(akira.Listener), args[2].(error))
	})
	return _c
}

func (_c *MockOnConnectionCloseHook_OnConnectionClose_Call) Return() *MockOnConnectionCloseHook_OnConnectionClose_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOnConnectionCloseHook_OnConnectionClose_Call) RunAndReturn(run func(*akira.Server, akira.Listener, error)) *MockOnConnectionCloseHook_OnConnectionClose_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnConnectionCloseHook creates a new instance of MockOnConnectionCloseHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnConnectionCloseHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnConnectionCloseHook {
	mock := &MockOnConnectionCloseHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
