// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockOnConnectedHook is an autogenerated mock type for the OnConnectedHook type
type MockOnConnectedHook struct {
	mock.Mock
}

type MockOnConnectedHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnConnectedHook) EXPECT() *MockOnConnectedHook_Expecter {
	return &MockOnConnectedHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnConnectedHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnConnectedHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnConnectedHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnConnectedHook_Expecter) Name() *MockOnConnectedHook_Name_Call {
	return &MockOnConnectedHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnConnectedHook_Name_Call) Run(run func()) *MockOnConnectedHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnConnectedHook_Name_Call) Return(_a0 string) *MockOnConnectedHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnConnectedHook_Name_Call) RunAndReturn(run func() string) *MockOnConnectedHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnConnected provides a mock function with given fields: c
func (_m *MockOnConnectedHook) OnConnected(c *akira.Client) {
	_m.Called(c)
}

// MockOnConnectedHook_OnConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnConnected'
type MockOnConnectedHook_OnConnected_Call struct {
	*mock.Call
}

// OnConnected is a helper method to define mock.On call
//   - c *akira.Client
func (_e *MockOnConnectedHook_Expecter) OnConnected(c interface{}) *MockOnConnectedHook_OnConnected_Call {
	return &MockOnConnectedHook_OnConnected_Call{Call: _e.mock.On("OnConnected", c)}
}

func (_c *MockOnConnectedHook_OnConnected_Call) Run(run func(c *akira.Client)) *MockOnConnectedHook_OnConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Client))
	})
	return _c
}

func (_c *MockOnConnectedHook_OnConnected_Call) Return() *MockOnConnectedHook_OnConnected_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOnConnectedHook_OnConnected_Call) RunAndReturn(run func(*akira.Client)) *MockOnConnectedHook_OnConnected_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnConnectedHook creates a new instance of MockOnConnectedHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnConnectedHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnConnectedHook {
	mock := &MockOnConnectedHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
