// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockOnPacketSendErrorHook is an autogenerated mock type for the OnPacketSendErrorHook type
type MockOnPacketSendErrorHook struct {
	mock.Mock
}

type MockOnPacketSendErrorHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnPacketSendErrorHook) EXPECT() *MockOnPacketSendErrorHook_Expecter {
	return &MockOnPacketSendErrorHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnPacketSendErrorHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnPacketSendErrorHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnPacketSendErrorHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnPacketSendErrorHook_Expecter) Name() *MockOnPacketSendErrorHook_Name_Call {
	return &MockOnPacketSendErrorHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnPacketSendErrorHook_Name_Call) Run(run func()) *MockOnPacketSendErrorHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnPacketSendErrorHook_Name_Call) Return(_a0 string) *MockOnPacketSendErrorHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnPacketSendErrorHook_Name_Call) RunAndReturn(run func() string) *MockOnPacketSendErrorHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnPacketSendError provides a mock function with given fields: c, p, err
func (_m *MockOnPacketSendErrorHook) OnPacketSendError(c *akira.Client, p akira.Packet, err error) {
	_m.Called(c, p, err)
}

// MockOnPacketSendErrorHook_OnPacketSendError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPacketSendError'
type MockOnPacketSendErrorHook_OnPacketSendError_Call struct {
	*mock.Call
}

// OnPacketSendError is a helper method to define mock.On call
//   - c *akira.Client
//   - p akira.Packet
//   - err error
func (_e *MockOnPacketSendErrorHook_Expecter) OnPacketSendError(c interface{}, p interface{}, err interface{}) *MockOnPacketSendErrorHook_OnPacketSendError_Call {
	return &MockOnPacketSendErrorHook_OnPacketSendError_Call{Call: _e.mock.On("OnPacketSendError", c, p, err)}
}

func (_c *MockOnPacketSendErrorHook_OnPacketSendError_Call) Run(run func(c *akira.Client, p akira.Packet, err error)) *MockOnPacketSendErrorHook_OnPacketSendError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Client), args[1].(akira.Packet), args[2].(error))
	})
	return _c
}

func (_c *MockOnPacketSendErrorHook_OnPacketSendError_Call) Return() *MockOnPacketSendErrorHook_OnPacketSendError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOnPacketSendErrorHook_OnPacketSendError_Call) RunAndReturn(run func(*akira.Client, akira.Packet, error)) *MockOnPacketSendErrorHook_OnPacketSendError_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnPacketSendErrorHook creates a new instance of MockOnPacketSendErrorHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnPacketSendErrorHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnPacketSendErrorHook {
	mock := &MockOnPacketSendErrorHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
