// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockOnPacketSentHook is an autogenerated mock type for the OnPacketSentHook type
type MockOnPacketSentHook struct {
	mock.Mock
}

type MockOnPacketSentHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnPacketSentHook) EXPECT() *MockOnPacketSentHook_Expecter {
	return &MockOnPacketSentHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnPacketSentHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnPacketSentHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnPacketSentHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnPacketSentHook_Expecter) Name() *MockOnPacketSentHook_Name_Call {
	return &MockOnPacketSentHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnPacketSentHook_Name_Call) Run(run func()) *MockOnPacketSentHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnPacketSentHook_Name_Call) Return(_a0 string) *MockOnPacketSentHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnPacketSentHook_Name_Call) RunAndReturn(run func() string) *MockOnPacketSentHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnPacketSent provides a mock function with given fields: c, p
func (_m *MockOnPacketSentHook) OnPacketSent(c *akira.Client, p akira.Packet) {
	_m.Called(c, p)
}

// MockOnPacketSentHook_OnPacketSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPacketSent'
type MockOnPacketSentHook_OnPacketSent_Call struct {
	*mock.Call
}

// OnPacketSent is a helper method to define mock.On call
//   - c *akira.Client
//   - p akira.Packet
func (_e *MockOnPacketSentHook_Expecter) OnPacketSent(c interface{}, p interface{}) *MockOnPacketSentHook_OnPacketSent_Call {
	return &MockOnPacketSentHook_OnPacketSent_Call{Call: _e.mock.On("OnPacketSent", c, p)}
}

func (_c *MockOnPacketSentHook_OnPacketSent_Call) Run(run func(c *akira.Client, p akira.Packet)) *MockOnPacketSentHook_OnPacketSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Client), args[1].(akira.Packet))
	})
	return _c
}

func (_c *MockOnPacketSentHook_OnPacketSent_Call) Return() *MockOnPacketSentHook_OnPacketSent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOnPacketSentHook_OnPacketSent_Call) RunAndReturn(run func(*akira.Client, akira.Packet)) *MockOnPacketSentHook_OnPacketSent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnPacketSentHook creates a new instance of MockOnPacketSentHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnPacketSentHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnPacketSentHook {
	mock := &MockOnPacketSentHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
