// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockOnPacketReceiveErrorHook is an autogenerated mock type for the OnPacketReceiveErrorHook type
type MockOnPacketReceiveErrorHook struct {
	mock.Mock
}

type MockOnPacketReceiveErrorHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnPacketReceiveErrorHook) EXPECT() *MockOnPacketReceiveErrorHook_Expecter {
	return &MockOnPacketReceiveErrorHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnPacketReceiveErrorHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnPacketReceiveErrorHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnPacketReceiveErrorHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnPacketReceiveErrorHook_Expecter) Name() *MockOnPacketReceiveErrorHook_Name_Call {
	return &MockOnPacketReceiveErrorHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnPacketReceiveErrorHook_Name_Call) Run(run func()) *MockOnPacketReceiveErrorHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnPacketReceiveErrorHook_Name_Call) Return(_a0 string) *MockOnPacketReceiveErrorHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnPacketReceiveErrorHook_Name_Call) RunAndReturn(run func() string) *MockOnPacketReceiveErrorHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnPacketReceiveError provides a mock function with given fields: c, err
func (_m *MockOnPacketReceiveErrorHook) OnPacketReceiveError(c *akira.Client, err error) error {
	ret := _m.Called(c, err)

	var r0 error
	if rf, ok := ret.Get(0).(func(*akira.Client, error) error); ok {
		r0 = rf(c, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOnPacketReceiveErrorHook_OnPacketReceiveError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPacketReceiveError'
type MockOnPacketReceiveErrorHook_OnPacketReceiveError_Call struct {
	*mock.Call
}

// OnPacketReceiveError is a helper method to define mock.On call
//   - c *akira.Client
//   - err error
func (_e *MockOnPacketReceiveErrorHook_Expecter) OnPacketReceiveError(c interface{}, err interface{}) *MockOnPacketReceiveErrorHook_OnPacketReceiveError_Call {
	return &MockOnPacketReceiveErrorHook_OnPacketReceiveError_Call{Call: _e.mock.On("OnPacketReceiveError", c, err)}
}

func (_c *MockOnPacketReceiveErrorHook_OnPacketReceiveError_Call) Run(run func(c *akira.Client, err error)) *MockOnPacketReceiveErrorHook_OnPacketReceiveError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Client), args[1].(error))
	})
	return _c
}

func (_c *MockOnPacketReceiveErrorHook_OnPacketReceiveError_Call) Return(_a0 error) *MockOnPacketReceiveErrorHook_OnPacketReceiveError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnPacketReceiveErrorHook_OnPacketReceiveError_Call) RunAndReturn(run func(*akira.Client, error) error) *MockOnPacketReceiveErrorHook_OnPacketReceiveError_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnPacketReceiveErrorHook creates a new instance of MockOnPacketReceiveErrorHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnPacketReceiveErrorHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnPacketReceiveErrorHook {
	mock := &MockOnPacketReceiveErrorHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
