// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockOnServerStartedHook is an autogenerated mock type for the OnServerStartedHook type
type MockOnServerStartedHook struct {
	mock.Mock
}

type MockOnServerStartedHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnServerStartedHook) EXPECT() *MockOnServerStartedHook_Expecter {
	return &MockOnServerStartedHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnServerStartedHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnServerStartedHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnServerStartedHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnServerStartedHook_Expecter) Name() *MockOnServerStartedHook_Name_Call {
	return &MockOnServerStartedHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnServerStartedHook_Name_Call) Run(run func()) *MockOnServerStartedHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnServerStartedHook_Name_Call) Return(_a0 string) *MockOnServerStartedHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnServerStartedHook_Name_Call) RunAndReturn(run func() string) *MockOnServerStartedHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnServerStarted provides a mock function with given fields: s
func (_m *MockOnServerStartedHook) OnServerStarted(s *akira.Server) {
	_m.Called(s)
}

// MockOnServerStartedHook_OnServerStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnServerStarted'
type MockOnServerStartedHook_OnServerStarted_Call struct {
	*mock.Call
}

// OnServerStarted is a helper method to define mock.On call
//   - s *akira.Server
func (_e *MockOnServerStartedHook_Expecter) OnServerStarted(s interface{}) *MockOnServerStartedHook_OnServerStarted_Call {
	return &MockOnServerStartedHook_OnServerStarted_Call{Call: _e.mock.On("OnServerStarted", s)}
}

func (_c *MockOnServerStartedHook_OnServerStarted_Call) Run(run func(s *akira.Server)) *MockOnServerStartedHook_OnServerStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server))
	})
	return _c
}

func (_c *MockOnServerStartedHook_OnServerStarted_Call) Return() *MockOnServerStartedHook_OnServerStarted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOnServerStartedHook_OnServerStarted_Call) RunAndReturn(run func(*akira.Server)) *MockOnServerStartedHook_OnServerStarted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnServerStartedHook creates a new instance of MockOnServerStartedHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnServerStartedHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnServerStartedHook {
	mock := &MockOnServerStartedHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
