// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockOnServerStoppedHook is an autogenerated mock type for the OnServerStoppedHook type
type MockOnServerStoppedHook struct {
	mock.Mock
}

type MockOnServerStoppedHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnServerStoppedHook) EXPECT() *MockOnServerStoppedHook_Expecter {
	return &MockOnServerStoppedHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnServerStoppedHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnServerStoppedHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnServerStoppedHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnServerStoppedHook_Expecter) Name() *MockOnServerStoppedHook_Name_Call {
	return &MockOnServerStoppedHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnServerStoppedHook_Name_Call) Run(run func()) *MockOnServerStoppedHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnServerStoppedHook_Name_Call) Return(_a0 string) *MockOnServerStoppedHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnServerStoppedHook_Name_Call) RunAndReturn(run func() string) *MockOnServerStoppedHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnServerStopped provides a mock function with given fields: s
func (_m *MockOnServerStoppedHook) OnServerStopped(s *akira.Server) {
	_m.Called(s)
}

// MockOnServerStoppedHook_OnServerStopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnServerStopped'
type MockOnServerStoppedHook_OnServerStopped_Call struct {
	*mock.Call
}

// OnServerStopped is a helper method to define mock.On call
//   - s *akira.Server
func (_e *MockOnServerStoppedHook_Expecter) OnServerStopped(s interface{}) *MockOnServerStoppedHook_OnServerStopped_Call {
	return &MockOnServerStoppedHook_OnServerStopped_Call{Call: _e.mock.On("OnServerStopped", s)}
}

func (_c *MockOnServerStoppedHook_OnServerStopped_Call) Run(run func(s *akira.Server)) *MockOnServerStoppedHook_OnServerStopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server))
	})
	return _c
}

func (_c *MockOnServerStoppedHook_OnServerStopped_Call) Return() *MockOnServerStoppedHook_OnServerStopped_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOnServerStoppedHook_OnServerStopped_Call) RunAndReturn(run func(*akira.Server)) *MockOnServerStoppedHook_OnServerStopped_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnServerStoppedHook creates a new instance of MockOnServerStoppedHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnServerStoppedHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnServerStoppedHook {
	mock := &MockOnServerStoppedHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
