// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockOnStartHook is an autogenerated mock type for the OnStartHook type
type MockOnStartHook struct {
	mock.Mock
}

type MockOnStartHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnStartHook) EXPECT() *MockOnStartHook_Expecter {
	return &MockOnStartHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnStartHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnStartHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnStartHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnStartHook_Expecter) Name() *MockOnStartHook_Name_Call {
	return &MockOnStartHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnStartHook_Name_Call) Run(run func()) *MockOnStartHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnStartHook_Name_Call) Return(_a0 string) *MockOnStartHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnStartHook_Name_Call) RunAndReturn(run func() string) *MockOnStartHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnStart provides a mock function with given fields: s
func (_m *MockOnStartHook) OnStart(s *akira.Server) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(*akira.Server) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOnStartHook_OnStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnStart'
type MockOnStartHook_OnStart_Call struct {
	*mock.Call
}

// OnStart is a helper method to define mock.On call
//   - s *akira.Server
func (_e *MockOnStartHook_Expecter) OnStart(s interface{}) *MockOnStartHook_OnStart_Call {
	return &MockOnStartHook_OnStart_Call{Call: _e.mock.On("OnStart", s)}
}

func (_c *MockOnStartHook_OnStart_Call) Run(run func(s *akira.Server)) *MockOnStartHook_OnStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server))
	})
	return _c
}

func (_c *MockOnStartHook_OnStart_Call) Return(_a0 error) *MockOnStartHook_OnStart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnStartHook_OnStart_Call) RunAndReturn(run func(*akira.Server) error) *MockOnStartHook_OnStart_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnStartHook creates a new instance of MockOnStartHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnStartHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnStartHook {
	mock := &MockOnStartHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
