// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockOnStopHook is an autogenerated mock type for the OnStopHook type
type MockOnStopHook struct {
	mock.Mock
}

type MockOnStopHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnStopHook) EXPECT() *MockOnStopHook_Expecter {
	return &MockOnStopHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnStopHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnStopHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnStopHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnStopHook_Expecter) Name() *MockOnStopHook_Name_Call {
	return &MockOnStopHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnStopHook_Name_Call) Run(run func()) *MockOnStopHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnStopHook_Name_Call) Return(_a0 string) *MockOnStopHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnStopHook_Name_Call) RunAndReturn(run func() string) *MockOnStopHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnStop provides a mock function with given fields: s
func (_m *MockOnStopHook) OnStop(s *akira.Server) {
	_m.Called(s)
}

// MockOnStopHook_OnStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnStop'
type MockOnStopHook_OnStop_Call struct {
	*mock.Call
}

// OnStop is a helper method to define mock.On call
//   - s *akira.Server
func (_e *MockOnStopHook_Expecter) OnStop(s interface{}) *MockOnStopHook_OnStop_Call {
	return &MockOnStopHook_OnStop_Call{Call: _e.mock.On("OnStop", s)}
}

func (_c *MockOnStopHook_OnStop_Call) Run(run func(s *akira.Server)) *MockOnStopHook_OnStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server))
	})
	return _c
}

func (_c *MockOnStopHook_OnStop_Call) Return() *MockOnStopHook_OnStop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOnStopHook_OnStop_Call) RunAndReturn(run func(*akira.Server)) *MockOnStopHook_OnStop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnStopHook creates a new instance of MockOnStopHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnStopHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnStopHook {
	mock := &MockOnStopHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
