// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	akira "github.com/gsalomao/akira"
	mock "github.com/stretchr/testify/mock"
)

// MockOnServerStopHook is an autogenerated mock type for the OnServerStopHook type
type MockOnServerStopHook struct {
	mock.Mock
}

type MockOnServerStopHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnServerStopHook) EXPECT() *MockOnServerStopHook_Expecter {
	return &MockOnServerStopHook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with given fields:
func (_m *MockOnServerStopHook) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOnServerStopHook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockOnServerStopHook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockOnServerStopHook_Expecter) Name() *MockOnServerStopHook_Name_Call {
	return &MockOnServerStopHook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockOnServerStopHook_Name_Call) Run(run func()) *MockOnServerStopHook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnServerStopHook_Name_Call) Return(_a0 string) *MockOnServerStopHook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnServerStopHook_Name_Call) RunAndReturn(run func() string) *MockOnServerStopHook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// OnServerStop provides a mock function with given fields: s
func (_m *MockOnServerStopHook) OnServerStop(s *akira.Server) {
	_m.Called(s)
}

// MockOnServerStopHook_OnServerStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnServerStop'
type MockOnServerStopHook_OnServerStop_Call struct {
	*mock.Call
}

// OnServerStop is a helper method to define mock.On call
//   - s *akira.Server
func (_e *MockOnServerStopHook_Expecter) OnServerStop(s interface{}) *MockOnServerStopHook_OnServerStop_Call {
	return &MockOnServerStopHook_OnServerStop_Call{Call: _e.mock.On("OnServerStop", s)}
}

func (_c *MockOnServerStopHook_OnServerStop_Call) Run(run func(s *akira.Server)) *MockOnServerStopHook_OnServerStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*akira.Server))
	})
	return _c
}

func (_c *MockOnServerStopHook_OnServerStop_Call) Return() *MockOnServerStopHook_OnServerStop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOnServerStopHook_OnServerStop_Call) RunAndReturn(run func(*akira.Server)) *MockOnServerStopHook_OnServerStop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnServerStopHook creates a new instance of MockOnServerStopHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnServerStopHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnServerStopHook {
	mock := &MockOnServerStopHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
